version: '2.1'
orbs:
  maven: circleci/maven@0.0.12
  slack: circleci/slack@4.0

workflows:
  maven_test:
    jobs:
      docker:
        - image: 'cimg/base:stable'
      - maven/test # checkout, build, test, and upload test results
        - slack/notify:
          channel: circleci
          event: pass
          template: success_tagged_deploy_1
        - slack/notify:
          channel: circle-ci
          event: fail
          template: basic_fail_1