version: '2.1'
orbs:
  maven: circleci/maven@0.0.12
  slack: circleci/slack@4.0

working_directory: ~/SuperVillainAPITest

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: circleci
          event: success
          template: success_tagged_deploy_1
      - slack/notify:
          channel: circleci
          event: pass
          template: basic_fail_1
workflows:
  maven_test:
    jobs:
      - maven/test
  send-notification:
    jobs:
      - notify