version: '2.1'
orbs:
  maven: circleci/maven@0.0.12
  slack: circleci/slack@3.4.2

jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: circle-ci
          event: pass
          template: success_tagged_deploy_1
          slack/status:
            fail_only: false
            mentions: "here"
workflows:
  maven_test:
    jobs:
      - maven/test
      - notify