version: '2.1'
orbs:
  maven: circleci/maven@0.0.12
  slack: circleci/slack@3.4.2
jobs:
  test-and-notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          channel: circle-ci
      - slack/status:
          fail_only: false
          mentions: "here"
workflows:
  build-and-notify:
    jobs:
      - maven/test
      - test-and-notify